---
## 部署k8s master组件

- name: 设置k8s master组件目录
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ k8s_cert_path }}"
    - "{{ k8s_conf_path }}"

- name: 上传k8s master组件相关文件
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest  }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: kube-apiserver, dest: "{{ k8s_bin_path }}/kube-apiserver", mode: "0755" }
    - { src: kube-controller-manager, dest: "{{ k8s_bin_path }}/kube-controller-manager", mode: "0755" }
    - { src: kube-scheduler, dest: "{{ k8s_bin_path }}/kube-scheduler", mode: "0755" }
    - { src: kubectl, dest: "{{ k8s_bin_path }}/kubectl", mode: "0755"  }
    - { src: controller-manager.kubeconfig, dest: "{{ k8s_conf_path }}/controller-manager.kubeconfig", mode: "0644"  }
    - { src: scheduler.kubeconfig, dest: "{{ k8s_conf_path }}/scheduler.kubeconfig", mode: "0644" }
    - { src: admin.kubeconfig, dest: "{{ k8s_conf_path }}/admin.kubeconfig", mode: "0644"  }
    - { src: ca.pem, dest: "{{ k8s_cert_path }}/ca.pem", mode: "0644" }
    - { src: ca-key.pem, dest: "{{ k8s_cert_path }}/ca-key.pem", mode: "0644"  }
    - { src: apiserver.pem, dest: "{{ k8s_cert_path }}/apiserver.pem", mode: "0644" }
    - { src: apiserver-key.pem, dest: "{{ k8s_cert_path }}/apiserver-key.pem", mode: "0644"  }
    - { src: etcd-ca.pem, dest: "{{ k8s_cert_path }}/etcd-ca.pem", mode: "0644" }
    - { src: etcd.pem, dest: "{{ k8s_cert_path }}/etcd.pem", mode: "0644" }
    - { src: etcd-key.pem, dest: "{{ k8s_cert_path }}/etcd-key.pem", mode: "0644" }
    - { src: front-proxy-ca.pem, dest: "{{ k8s_cert_path }}/front-proxy-ca.pem", mode: "0644"  }
    - { src: front-proxy-ca-key.pem, dest: "{{ k8s_cert_path }}/front-proxy-ca-key.pem", mode: "0644" }
    - { src: front-proxy-client-key.pem, dest: "{{ k8s_cert_path }}/front-proxy-client-key.pem", mode: "0644" }
    - { src: front-proxy-client.pem, dest: "{{ k8s_cert_path }}/front-proxy-client.pem", mode: "0644" }
    - { src: sa.key, dest: "{{ k8s_cert_path }}/sa.key", mode: "0644" }
    - { src: sa.pub, dest: "{{ k8s_cert_path }}/sa.pub", mode: "0644" }

- name: 上传k8s master组件相关模板文件
  ansible.builtin.template:
    src: "{{ item.src  }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: kube-apiserver.service.j2, dest: /usr/lib/systemd/system/kube-apiserver.service }
    - { src: kube-controller-manager.service.j2, dest: /usr/lib/systemd/system/kube-controller-manager.service }
    - { src: kube-scheduler.service.j2, dest: /usr/lib/systemd/system/kube-scheduler.service }
    - { src: bootstrap.secret.yml.j2, dest: "{{ k8s_conf_path }}/bootstrap.secret.yml" }
    - { src: token.csv.j2, dest: "{{ k8s_conf_path }}/token.csv" }

- name: 启动k8s master组件
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: 配置admin.kubeconfig
  ansible.builtin.shell: |
    sudo mkdir ~/.kube
    sudo chown $(id -u):$(id -g) ~/.kube
    sudo chmod 0600 ~/.kube
    sudo cp {{ k8s_conf_path }}/admin.kubeconfig ~/.kube/config

- name: 配置k8s集群组件相关权限
  ansible.builtin.shell: |
    sudo {{ k8s_bin_path }}/kubectl apply -f {{ k8s_conf_path }}/bootstrap.secret.yml