---
# Source: imux/templates/rbac.yaml
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: imux
---
# Source: imux/templates/rbac.yaml
# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: imux
rules:
- apiGroups: [""] # 核心API组
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create"]
---
# Source: imux/templates/rbac.yaml
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: imux
subjects:
- kind: ServiceAccount
  name: imux
roleRef:
  kind: Role
  name: imux
  apiGroup: rbac.authorization.k8s.io
---
# Source: imux/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: imux
  labels:
    app.kubernetes.io/name: imux
    app.kubernetes.io/instance: imux
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 9990
      targetPort: 9990
      nodePort: 30001
  selector:
    app.kubernetes.io/name: imux
    app.kubernetes.io/instance: imux
---
# Source: imux/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imux
  labels:
    app.kubernetes.io/name: imux
    app.kubernetes.io/instance: imux
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: imux
      app.kubernetes.io/instance: imux
  template:
    metadata:
      labels:
        app.kubernetes.io/name: imux
        app.kubernetes.io/instance: imux
    spec:
      serviceAccountName: imux
      containers:
        - name: imux
          image: "web-harbor.xxxxx.com/hh/imux@sha256:ff8fc26a38672b4e4dd4ca1d777650307f7e649201b21dd5ad6d466c7fc1566a"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9990
---
# Source: imux/templates/gateway.yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: imux-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
---
# Source: imux/templates/httproute.yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: imux-route
spec:
  parentRefs:
    - name: imux-gateway
      namespace: default
  hostnames:
    - "api.imux.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/*
      backendRefs:
        - name: imux
          port: 9990

