---
# contaierd服务部署

- name: 上传containerd服务需要的二进制包
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "containerd-{{ containerd_version }}-linux-amd64.tar.gz", dest: "/tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz" }
    - { src: runc.amd64, dest: "/tmp/runc.amd64" }
    - { src: "cni-plugins-linux-amd64-v{{ cni_version }}.tgz", dest: "/tmp/cni-plugins-linux-amd64-v{{ cni_version }}.tgz" } 

- name: 安装containerd相关包
  ansible.builtin.shell:
    cmd: |
      tar -xf /tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz -C /usr/local
      install -m 755 /tmp/runc.amd64 /usr/local/sbin/runc
      mkdir -p /opt/cni/bin
      tar -xf /tmp/cni-plugins-linux-amd64-v{{ cni_version }}.tgz -C /opt/cni/bin

- name: 上传containerd systemd服务配置文件
  ansible.builtin.template:
    src: containerd.service.j2
    dest: /usr/lib/systemd/system/containerd.service

- name: 创建containerd配置目录
  ansible.builtin.file:
    path: /etc/containerd
    state: directory

- name: 配置containred所需内核模块
  ansible.builtin.template:
    src: "containerd.conf.j2"
    dest: "/etc/modules-load.d/containerd.conf"
    mode: 0755
  notify:
    - restart systemd-modules-load

- name: 上传containerd配置文件
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml

- name: 启动containerd服务
  ansible.builtin.systemd:
    name: containerd
    daemon_reload: true
    enabled: true
    state: restarted