- name: restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: true
  become: true

- name: restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
    enabled: true
  become: true