apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "imux.fullname" . }}-route
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - "{{ .Values.gateway.hostname }}"
  rules:
    - matches:
        - path:
            type: {{ .Values.route.pathType }}
            value: {{ .Values.route.path }}
      backendRefs:
        - name: {{ include "imux.fullname" . }}
          port: {{ .Values.service.port }}